version: "3"

services: 
    database:
        image: mysql/mysql-server:latest
        ports: 
            - 3306:3306 # Remove as this will be accessed within docker
        volumes: 
            - ./mysqlData:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=secret

    users:
        image: driverse/users:latest
        restart: always

    rides:
        image: driverse/rides:latest
        restart: always
    
    api-gateway:
        image: nginx:latest
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
    prometheus:
        image: prom/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml
        restart: always
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        
    grafana:
        image: grafana/grafana
        user: "$UID:$GID"
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./grafana/data:/var/lib/grafana

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        restart: always
        command:
            - '--path.rootfs=/host'
        pid: host
        volumes:
            - '/:/host:ro,rslave'

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            


