# Compose: docker-compose up
# Swarm: 
#   docker swarm init
#   docker stack deploy --prune --compose-file docker-compose.yml driverse
#   docker stack services driverse
#   sudo docker stack rm driverse   

version: "3.7"

services: 
    database:
        image: mysql/mysql-server:latest
        ports: 
            - 3306:3306 # Remove as this will be accessed within docker
        volumes: 
            - ./mysqlData:/var/lib/mysql
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=secret

    users:
        image: driverse/users:latest
        deploy:
            mode: replicated
            replicas: 3
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    rides:
        image: driverse/rides:latest
        deploy:
            mode: replicated
            replicas: 3
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
    
    api-gateway:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
    prometheus:
        image: prom/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        
    grafana:
        image: grafana/grafana
        user: "$UID:$GID"
        ports:
            - 3000:3000
        volumes:
            - ./grafana/data:/var/lib/grafana

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        command:
            - '--path.rootfs=/host'
        volumes:
            - '/:/host:ro,rslave'

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            


